docking_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 50.0
    initial_perception_timeout: 5.0
    wait_charge_timeout: 5.0
    dock_approach_timeout: 30.0
    undock_linear_tolerance: 0.05
    undock_angular_tolerance: 0.05
    max_retries: 3
    base_frame: "base_link"
    fixed_frame: "odom"
    dock_backwards: true
    dock_prestaging_tolerance: 0.01

    # Types of docks
    dock_plugins: ['simple_dock']
    simple_dock:
      plugin: 'neo_docking2::NeoDock'
      docking_threshold: 0.01
      staging_x_offset: 1.2
      staging_yaw_offset: 0.0

      use_external_detection_pose: true
      use_battery_status: false
      use_stall_detection: false

      external_detection_timeout: 2.0
      external_detection_translation_x: 0.0 # negative
      external_detection_translation_y: 0.0
      external_detection_rotation_roll: 0.0
      external_detection_rotation_pitch: 0.0
      external_detection_rotation_yaw: 0.0
      filter_coef: 0.1

    # Sep. file of dock instances so config file can be used in multiple locations
    dock_database: ''

    controller:
      k_phi: 15.0
      k_delta: 15.0
      v_linear_min: 0.1
      v_linear_max: 0.25
      max_angular_velocity: 0.3
      slowdown_radius: 0.5
